In [1]:
# Technical challenge DE

In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import requests

/var/folders/wb/w8733cqs7_sffw0hk4dmjv1h0000gn/T/ipykernel_45451/108459589.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# Import the dataset
flights_inf = 'challenge_dataset.csv'

In [3]:
# Create the flight Dataframe
flights_df = pd.read_csv(flights_inf)

flights_df.head(10)

,origin,destination,airline,flight_num,origin_iata_code,origin_name,origin_latitude,origin_longitude,destination_iata_code,destination_name,destination_latitude,destination_longitude
0,TLC,MTY,4O,104,TLC,Licenciado Adolfo Lopez Mateos International A...,19.3371,-99.5660,MTY,General Mariano Escobedo International Airport,25.7785,-100.1070
1,MTY,TLC,4O,119,MTY,General Mariano Escobedo International Airport,25.7785,-100.1070,TLC,Licenciado Adolfo Lopez Mateos International A...,19.3371,-99.5660
2,MEX,MTY,4O,2100,MEX,Licenciado Benito Juarez International Airport,19.4363,-99.0721,MTY,General Mariano Escobedo International Airport,25.7785,-100.1070
3,MTY,MEX,4O,2101,MTY,General Mariano Escobedo International Airport,25.7785,-100.1070,MEX,Licenciado Benito Juarez International Airport,19.4363,-99.0721
4,MEX,MTY,4O,2102,MEX,Licenciado Benito Juarez International Airport,19.4363,-99.0721,MTY,General Mariano Escobedo International Airport,25.7785,-100.1070
5,MEX,MTY,4O,2102,MEX,Licenciado Benito Juarez International Airport,19.4363,-99.0721,MTY,General Mariano Escobedo International Airport,25.7785,-100.1070
6,MEX,MTY,4O,2102,MEX,Licenciado Benito Juarez International Airport,19.4363,-99.0721,MTY,General Mariano Escobedo International Airport,25.7785,-100.1070
7,MEX,MTY,4O,2102,MEX,Licenciado Benito Juarez International Airport,19.4363,-99.0721,MTY,General Mariano Escobedo International Airport,25.7785,-100.1070
8,MEX,MTY,4O,2102,MEX,Licenciado Benito Juarez International Airport,19.4363,-99.0721,MTY,General Mariano Escobedo International Airport,25.7785,-100.1070
9,MEX,MTY,4O,2102,MEX,Licenciado Benito Juarez International Airport,19.4363,-99.0721,MTY,General Mariano Escobedo International Airport,25.7785,-100.1070

In [4]:
# Get unique origin and destination combinations
unique_fligts = flights_df.groupby(['origin_iata_code', 'destination_iata_code']).size().reset_index(name='Conteo')

# Get the latitudes and longitudes for each unique combination
for index, row in unique_fligts.iterrows():
    origin = row['origin_iata_code']
    destination = row['destination_iata_code']
    latitude_origin = flights_df.loc[flights_df['origin_iata_code'] == origin, 'origin_latitude'].iloc[0]
    longitude_origen = flights_df.loc[flights_df['origin_iata_code'] == origin, 'origin_longitude'].iloc[0]
    latitude_destination = flights_df.loc[flights_df['destination_iata_code'] == destination, 'destination_latitude'].iloc[0]
    longitude_destination = flights_df.loc[flights_df['destination_iata_code'] == destination, 'destination_longitude'].iloc[0]
    unique_fligts.at[index, 'origin_latitude'] = latitude_origin
    unique_fligts.at[index, 'origin_longitude'] = longitude_origen
    unique_fligts.at[index, 'destination_latitude'] = latitude_destination
    unique_fligts.at[index, 'destination_longitude'] = longitude_destination
    
df_unique_fligts = pd.DataFrame(unique_fligts)
df_unique_fligts.tail(20)

,origin_iata_code,destination_iata_code,Conteo,origin_latitude,origin_longitude,destination_latitude,destination_longitude
70,MTY,GDL,1,25.7785,-100.1070,20.5218,-103.3110
71,MTY,MEX,25,25.7785,-100.1070,19.4363,-99.0721
72,MTY,MIA,9,25.7785,-100.1070,25.7932,-80.2906
73,MTY,TLC,2,25.7785,-100.1070,19.3371,-99.5660
74,OAX,MEX,1,16.9999,-96.7266,19.4363,-99.0721
75,PBC,DFW,1,19.1581,-98.3714,32.8968,-97.0380
76,PVR,DFW,5,20.6801,-105.2540,32.8968,-97.0380
77,PVR,MEX,10,20.6801,-105.2540,19.4363,-99.0721
78,PXM,MEX,2,15.8769,-97.0891,19.4363,-99.0721
79,QRO,DFW,20,20.6173,-100.1860,32.8968,-97.0380
80,SLP,DFW,16,22.2543,-100.9310,32.8968,-97.0380
81,TAM,MEX,29,22.2964,-97.8659,19.4363,-99.0721
82,TIJ,MEX,2,32.5411,-116.9700,19.4363,-99.0721
83,TLC,MTY,2,19.3371,-99.5660,25.7785,-100.1070
84,TRC,DFW,1,25.5683,-103.4110,32.8968,-97.0380
85,VER,MEX,16,19.1459,-96.1873,19.4363,-99.0721
86,VER,MID,2,19.1459,-96.1873,20.9370,-89.6577
87,VSA,MID,3,17.9970,-92.8174,20.9370,-89.6577
88,ZCL,MEX,1,22.8971,-102.6870,19.4363,-99.0721
89,ZIH,MEX,5,17.6016,-101.4610,19.4363,-99.0721